apiVersion: v1
kind: Service
metadata:
  name: addservice
  labels:
    run: addservice
spec:
  ports:
  - port: 8080
  name: main 
  protocol: TCP
  targetPort: 8080
  selector:
    run: addservice
  type: NodePort