apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: addservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: addservice
    spec:
      containers:
      - name: addservice
        image: kjmatsuda/addservice
        ports:
        - containerPort: 8080