pipeline {
  agent any

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Build') {
      steps {
        sh 'source ~/.bashrc && cd addservice && npm install'
      }
    }
    stage('Test'){
      steps {
        sh 'source ~/.bashrc && cd addservice && npm test'
      }
    }
    stage('Container'){
      steps {
      sh 'source ~/.bashrc && cd addservice && sh build.sh container'
      }
    }
    stage('Deploy'){
      steps {
      sh 'source ~/.bashrc && cd addservice && sh build.sh deploy'
      }
    }
  }
}